=== kit-transue/software-emancipation-discover/parsercmd/data/cmdline.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT cmdline (#PCDATA|translate|list|compilername|alternate)*>
<!ATTLIST cmdline
  nameintro CDATA #IMPLIED
  flagintro CDATA #IMPLIED
>
<!ELEMENT translate (filesuffix|option)*>
<!ATTLIST translate
  unrecognized CDATA #IMPLIED
>
<!ELEMENT option ANY>
<!ATTLIST option
  name CDATA #IMPLIED
  flag CDATA #IMPLIED
  immarg CDATA #IMPLIED
  separg CDATA #IMPLIED
  remarg CDATA #IMPLIED
  noarg CDATA #IMPLIED
  intro CDATA #IMPLIED
>
<!ELEMENT filesuffix ANY>
<!ATTLIST filesuffix
  name CDATA #IMPLIED
  foldcase CDATA #IMPLIED
>
<!ELEMENT list ANY>
<!ATTLIST list
  getenv CDATA #IMPLIED
  separator CDATA #IMPLIED
>
<!ELEMENT compilername (#PCDATA)*>
<!ELEMENT alternate EMPTY >
<!ATTLIST alternate nameintro CDATA #IMPLIED >

=== kit-transue/software-emancipation-discover/parsercmd/data/ntjvc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<cmdline nameintro="-" unrecognized="no_message">
<compilername>Visual J++</compilername>
java -w
<translate>
  <option name="cp"   separg="1">--classpath %</option>  <!-- sets effective CLASSPATH -->
  <option name="cp:p" separg="1">--classpath %</option>  <!-- prepends arg to effective CLASSPATH -->
  <option name="cp:a" separg="1">--classpath %</option>  <!-- appends arg to effective CLASSPATH -->
  <option name="nowarn" noarg="1">-w</option>
  <option name="w0" noarg="1">-w</option>
  <option name="w1" noarg="1">-w</option>
</translate>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/gcc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<!-- The language for a GCC compilation is based the suffix,
     possibly overridden by -x <language>.
     If no suffix is recognized, the gcc compiler does not default to
     C or C++, but assumes an object file which we need to ignore.
  -->
<cmdline nameintro="-" unrecognized="no_message">
<compilername>GNU C/C++</compilername>
reconfigure object
<translate>
  <filesuffix name="cpp">gcccpp(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="cxx">gcccpp(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="cc">gcccpp(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="c">gccc(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="C">gcccpp(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="h">gccc(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="i">gccc(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>
  <filesuffix name="ii">gcccpp(%0%)(%1%)(%2%)(%3%)(%4%)</filesuffix>

  <option name="x" immarg="1" separg="1">gcc%(%0%)(%1%)(%2%)(%3%)(%4%)</option>
				<!-- Incomplete implementation of this option.  The argument
				     should determine the language as follows:
					 -x c               C    gccc  support
					 -x c-header        C    gccc
					 -x cpp-output      C    gccc (?)
					 -x c++             C++  gcccpp   support
					 -x c++-cpp-output  C++  gcccpp
                                     But this file can't support it
				     due to parsercmd limitations. -->
</translate>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/hpansic.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<cmdline nameintro="-" unrecognized="warning"><alternate nameintro="+"/>
<compilername>HP ANSI C</compilername>
C -D__hp9000s800 -D__hppa -D__hpux -D__unix -D_PA_RISC2_0 -I/usr/include --c --no_warnings -D_SIZE_T --diag_suppress 265 --microsoft --size_t_is_unsigned_long -D_HPUX_SOURCE -D_PA_RISC2_0 -D__HP_CXD_SPP -D__STDC_EXT__ -D__STDC__ -D__hp9000s700
  <translate>
    <option name="Aa" noarg="1">-U_HPUX_SOURCE</option> <!-- -Aa  ANSI C -->
    <option name="Ac" noarg="1"/>                       <!-- -Ac  HP C version 3.1 compatibility -->
    <option name="Ae" noarg="1">-D_HPUX_SOURCE</option> <!-- -Ae  ANSI C with HP exts -->
    <option name="b" noarg="1"/>                        <!-- -b  unknown option ignored -->
    <option name="Bextern" noarg="1"/>                  <!-- -Bextern -->
    <option name="c" noarg="1"/>                        <!-- -c  no link -->
    <option name="C" noarg="1"/>                        <!-- -C  No preprocessor stripping comments. -->
    <option name="D" immarg="1" separg="1">-D%</option> <!-- -Dname -->
    <option name="dynamic" noarg="1"/>                  <!-- -dynamic  PIC objects -->
    <option name="E" noarg="1">-E</option>              <!-- -E  Preprocessing only, output to stdout. -->
    <option name="fast" noarg="1"/>                     <!-- -fast  optimize generated code -->
    <option name="g" noarg="1"/>                        <!-- -g  debugger info -->
    <option name="G" noarg="1"/>                        <!-- -G  gprof info -->
    <option name="I" immarg="1" separg="1">-I%</option> <!-- -Idir  -->
    <option name="l" immarg="1"/>                       <!-- -lx  links with /lib/libx.a and /usr/lib/libx.a -->
    <option name="L" immarg="1"/>                       <!-- -Ldir  Aadd dir to library search path. -->
    <option name="n" noarg="1"/>                        <!-- -n  shareable code -->
    <option name="N" noarg="1"/>                        <!-- -N  unshareable code -->
    <option name="noshared" noarg="1"/>                 <!-- -noshared  Statically-bound executable. -->
    <option name="o" separg="1"/>                       <!-- -o outfile  object modules to outfile -->
    <option name="O" noarg="1"/>                        <!-- -O  optimize level 2 -->
    <option name="p" noarg="1"/>                        <!-- -p  prof info -->
    <option name="P" noarg="1">-P</option>              <!-- -P  preprocess only, output to .i file. -->
    <option name="q" noarg="1"/>                        <!-- -q  demand loadable executable -->
    <option name="Q" noarg="1"/>                        <!-- -Q  not demand loadable executable -->
    <option name="s" noarg="1"/>                        <!-- -s  strip symbol table from executable -->
    <option name="S" noarg="1"/>                        <!-- -S  generate asm -->
    <option name="t" immarg="1" separg="1"/>            <!-- -t x,name  compiler subprocess control -->
    <option name="U" immarg="1" separg="1">-U%</option> <!-- -Uname  -->
    <option name="v" noarg="1"/>                        <!-- -v  verbose -->
    <option name="V" noarg="1"/>                        <!-- -V  subprocess version info to stderr -->
    <option name="w" noarg="1">-w</option>              <!-- -w  no warnings -->
    <option name="Wd" immarg="1"/>                      <!-- -Wd,-a  linker control -->
    <option name="W" immarg="1"/>                       <!-- -Wx, arg1 [,arg2,..,argn]  args to subprocess -->
    <option name="y" noarg="1"/>                        <!-- -y  HP SoftBench info -->
    <option name="Y" noarg="1"/>                        <!-- -Y  NLS -->
    <option name="z" noarg="1"/>                        <!-- -z  dereferencing null pointer is fatal -->
    <option name="Z" noarg="1"/>                        <!-- -Z  dereferencing null pointer is zero -->
    <option intro="+" name="a" noarg="1"/>              <!-- +a  linker control -->
    <option intro="+" name="DA" immarg="1"/>            <!-- +DAmodel  gen code for specific architecture -->
    <option intro="+" name="DC" immarg="1"/>            <!-- +DCapptype  gen code for embedded -->
    <option intro="+" name="DD32" noarg="1"/>           <!-- +DD32  gen 32-bit code for PA1.1 -->
    <option intro="+" name="DD64" noarg="1"/>           <!-- +DD64  gen 64-bit code for PA2.0 -->
    <option intro="+" name="d" immarg="1"/>             <!-- +dfname  optimization profile -->
    <option intro="+" name="DS" immarg="1"/>            <!-- +DSmodel  control scheduling optimization -->
    <option intro="+" name="DO" immarg="1"/>            <!-- +DOosname  specify target OS -->
    <option intro="+" name="e" noarg="1"/>              <!-- +e  extensions -->
    <option intro="+" name="ESfic" noarg="1"/>          <!-- +ESfic  optimization -->
    <option intro="+" name="ESconstlit" noarg="1"/>     <!-- +ESconstlit  const literals in read-only memory. -->
    <option intro="+" name="ESlit" noarg="1"/>          <!-- +ESlit  string literals and constants in read-only -->
    <option intro="+" name="ESnolit" noarg="1"/>        <!-- +ESnolit  not const literals in read-only memory -->
    <option intro="+" name="ESnoparmreloc" noarg="1"/>  <!-- +ESnoparmreloc  optimization -->
    <option intro="+" name="ESsfc" noarg="1"/>          <!-- +ESsfc  optimization -->
    <option intro="+" name="f" noarg="1"/>              <!-- +f  no promote float to double, except calls -->
    <option intro="+" name="FPflags" noarg="1"/>        <!-- +FPflags  FP traps -->
    <option intro="+" name="help" noarg="1"/>           <!-- +help -->
    <option intro="+" name="hugesize" noarg="1"/>       <!-- +hugesize  controls huge data -->
    <option intro="+" name="I" noarg="1"/>              <!-- +I  profiling data collection -->
    <option intro="+" name="k" noarg="1"/>              <!-- +k  code gen control -->
    <option intro="+" name="L" noarg="1"/>              <!-- +L  pragma & listing -->
    <option intro="+" name="m" noarg="1"/>              <!-- +m  controls listing -->
    <option intro="+" name="M" noarg="1"/>              <!-- +M  migration warnings -->
    <option intro="+" name="M0" noarg="1"/>             <!-- +M0  migration warnings -->
    <option intro="+" name="M1" noarg="1"/>             <!-- +M1  migration warnings -->
    <option intro="+" name="M2" noarg="1"/>             <!-- +M2  migration warnings -->
    <option intro="+" name="o" noarg="1"/>              <!-- +o  controls listing -->
    <option intro="+" name="objdebug" noarg="1"/>       <!-- +[no]objdebug -->
    <option intro="+" name="noobjdebug" noarg="1"/>     <!-- +[no]objdebug -->
    <option intro="+" name="O" immarg="1"/>             <!-- +Oopt  opt level -->
    <option intro="+" name="P" noarg="1"/>              <!-- +P  opt -->
    <option intro="+" name="pa" noarg="1"/>             <!-- +pa  profiling -->
    <option intro="+" name="pal" noarg="1"/>            <!-- +pal  profiling -->
    <option intro="+" name="pgmname" noarg="1"/>        <!-- +pgmname  optimization -->
    <option intro="+" name="r" noarg="1"/>              <!-- +r  no promote float to double -->
    <option intro="+" name="sb" noarg="1"/>             <!-- +sb  signed bit-fields -->
    <option intro="+" name="u" immarg="1"/>             <!-- +ubytes  alignment -->
    <option intro="+" name="uc" noarg="1">-u</option>   <!-- +uc  char is unsigned char -->
    <option intro="+" name="v" noarg="1">+w</option>    <!-- +v unknown option ignored -->
    <option intro="+" name="w" immarg="1"/>             <!-- +wn  warning control -->
    <option intro="+" name="W" separg="1"/>             <!-- +W n1[,n2,...nN]  warning suppression -->
    <option intro="+" name="We" separg="1"/>            <!-- +Wen1[,n2,...nN]  warnings are error -->
    <option intro="+" name="Ww" separg="1"/>            <!-- +Wwn1[,n2,...nN]  enable warnings -->
    <option intro="+" name="z" noarg="1"/>              <!-- +z  shared library object code -->
    <option intro="+" name="Z" noarg="1"/>              <!-- +Z  shared library object code -->
  </translate>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/mipsccpp.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<cmdline nameintro="-" unrecognized="no_message">
<compilername>MIPSpro C++</compilername>
  <switch enable="ntt"/> <!-- default to n32 -->
  <translate>
    <option name="n32" noarg="1" enable="ntt"/>
    <option name="o32" noarg="1" enable="ott"/>
    <option name="64" noarg="1" enable="sf"/>
  </translate>
  <switch when="ott|sf" disable="ntt"/>
CPP
    -w
    --allow_error_directive
    -D__DISCOVER__
    -D_WCHAR_T
    -D__STDC__=0
    -I%0%/include/CC
    -I%0%/include/CC/std
    -D_LANGUAGE_C_PLUS_PLUS
    -D_MIPS_SZINT=32
    -D_LONGLONG
    -D_WCHAR_T_IS_KEYWORD
    -D_BOOL
    -D__EDG_ABI_COMPATIBILITY_VERSION=229
    -D_COMPILER_VERSION=721
    -D_NAMESPACES
    -D_PARTIAL_SPECIALIZATION_OF_CLASS_TEMPLATES
    -D_TYPENAME_IS_KEYWORD
    -D_MEMBER_TEMPLATES
    -D_EXPLICIT_IS_KEYWORD
    -D__EXCEPTIONS
    -D__EXTENSIONS__
    -D__mips
    -D__sgi
    -Dsgi
    -D_SGI_SOURCE
    -D__cplusplus
    -D_MIPSEB
    -D__unix
  <switch when="ott"> <!-- o32 -->
    -D_MIPS_SIM=1
    -D_MIPS_FPSET=16
    -D_MIPS_SZLONG=32
    -D_MIPS_SZPTR=32
    -D_ABIO32=1
    -D_MIPS_ISA=2
  </switch>
  <switch when="ntt"> <!-- n32 -->
    -D_MIPS_SIM=2
    -D_MIPS_FPSET=32
    -D_MIPS_SZLONG=32
    -D_MIPS_SZPTR=32
    -D_ABIN32=2
    -D_MIPS_ISA=4
  </switch>
  <switch when="sf"> <!-- 64 -->
    -D_MIPS_SIM=3
    -D_MIPS_FPSET=32
    -D_MIPS_SZLONG=64
    -D_MIPS_SZPTR=64
    -D_ABI64=3
    -D_MIPS_ISA=4
  </switch>
  <translate>
    <option name="D" immarg="1">-D%</option>          <!-- Associate name with token as if by #define -->
    <option name="E" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to stdout -->
    <option name="I" immarg="1">-I%</option>          <!-- Add <dir> to preprocessor #include file search path -->
    <option name="P" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to .i  file -->
    <option name="U" immarg="1">-U%</option>          <!-- Delete initial definition of preprocessor symbol <name> -->
    <option name="v" noarg="1"></option>              <!-- Do stricter semantic checking -->
    <option name="w" noarg="1"></option>              <!-- Suppress compiler warning messages -->
    <option name="Xa" noarg="1"></option>             <!-- Compile assuming ANSI C conformance, allow K & R extensions (default mode) -->
    <option name="Xc" noarg="1">--strict</option>     <!-- Compile assuming strict ANSI C conformance -->
    <option name="Xs" noarg="1">--old_c</option>      <!-- Compile assuming (pre-ANSI) K & R C style code -->
    <option name="Xt" noarg="1">--old_c</option>      <!-- Compile assuming K & R conformance, allow ANSI C -->
    <option name="xCC" noarg="1"></option>            <!-- Accept C++ style comments -->
    <option name="xsfpconst" noarg="1"></option>      <!-- Represent unsuffixed floating point constants as single precision -->
    <option name="YI" immarg="1"></option>            <!-- Change default directory searched for include files -->
    <option name="xwe" noarg="1">-w2</option>         <!-- Convert all warnings to errors -->

    <option name="o" separg="1"></option>             <!-- Set name of output file to <outputfile> -->
    <option name="targ" separg="1">-TARG:</option>    <!-- Set target architecture to arch-type -->
    <option name="xinline" immarg="1">-INLINE:%</option> <!-- Same as -inline, takes file names in brackets. -->
  </translate>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/suncc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<!-- To verify these defaults, use cc -### filename. -->
<cmdline nameintro="-" unrecognized="no_message">
<compilername>Sun cc</compilername>
C
    --no_microsoft
    -D__DISCOVER__
    --c
    -D__SunOS_%1%
    -D__SUNPRO_C=0x500
    -D__SVR4
    -D__unix
    -D__sun
    -D__sparc
    -D__BUILTIN_VA_ARG_INCR
    -D__PRAGMA_REDEFINE_EXTNAME
    -Dunix
    -Dsun
    -Dsparc
    -D__RESTRICT
    --no_warnings
    --allow_error_directive
    -D__STDC__=0
    -D__builtin_va_alist=(*(char*)0)
<translate>
  <option name="D" immarg="1" separg="1">-D%</option><!-- Associate name with token as if by #define -->
  <option name="E" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to stdout -->
  <option name="I" immarg="1" separg="1">-I%</option><!-- Add <dir> to preprocessor #include file search path -->
  <option name="P" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to .i  file -->
  <option name="U" immarg="1">-U%</option>          <!-- Delete initial definition of preprocessor symbol <name> -->
  <option name="v" noarg="1"></option>              <!-- Do stricter semantic checking -->
  <option name="w" noarg="1"></option>              <!-- Suppress compiler warning messages -->
  <option name="Xa" noarg="1"></option>             <!-- Compile assuming ANSI C conformance, allow K & R extensions (default mode) -->
  <option name="Xc" noarg="1">--strict</option>     <!-- Compile assuming strict ANSI C conformance -->
  <option name="Xs" noarg="1">--old_c</option>      <!-- Compile assuming (pre-ANSI) K & R C style code -->
  <option name="Xt" noarg="1">--old_c</option>      <!-- Compile assuming K & R conformance, allow ANSI C -->
  <option name="xCC" noarg="1"></option>            <!-- Accept C++ style comments -->
  <option name="xsfpconst" noarg="1"></option>      <!-- Represent unsuffixed floating point constants as single precision -->
  <option name="YI" immarg="1"></option>            <!-- Change default directory searched for include files -->

  <option name="h" separg="1"></option>             <!-- Assign <name> to generated dynamic shared library -->
  <option name="o" separg="1"></option>             <!-- Set name of output file to <outputfile> -->
</translate>
<switch when="!(&quot;%0%&quot;==&quot;&quot;)">
    -I%0%/include/cc
</switch>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/sunccpp.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<!-- To verify these defaults, use CC -dryrun filename. -->
<cmdline nameintro="-" unrecognized="warning"><alternate nameintro="+"/>
<compilername>Sun WorkShop C++</compilername>
CPP
    --no_warnings
    --allow_error_directive
    --sun
    --nonconst_ref_anachronism
    -D__DISCOVER__
    -D__cplusplus=199711L
    -D_WCHAR_T=
    -D_BOOL
    -D__STDC__=0
    -D__SunOS_%1%
    -D__SUNPRO_CC=0x500
    -Dunix
    -Dsun
    -Dsparc
    -D__sparc
    -D__unix
    -D__sun
    -D__BUILTIN_VA_ARG_INCR
    -D__PRAGMA_REDEFINE_EXTNAME
    -D__SVR4
    -D__SUNPRO_CC_COMPAT=5
    -D__builtin_va_alist=(*(char*)0)
    -D__builtin_va_arg_incr(X)=X
    --c++
    -I/usr/include
    -I-
<translate>                                                   <!-- Add 'unrecognized="1"' here if log uses backslash-quote. -->
  <option name="D"    immarg="1" separg="1">-D%</option>      <!-- Define preprocessor symbol X -->
  <option name="E"    noarg="1">-E</option>                   <!-- Compile source through preprocessor only, output to stdout -->
  <option name="H"    noarg="1"></option>                     <!-- Print path names of included files -->
  <option name="I"    immarg="1">-I%</option>                 <!-- Add directory dir to INCLUDE and #include file search path -->
  <option name="P"    noarg="1">-E</option>                   <!-- Compile source through preprocessor only, output to .i file -->
  <option name="Qoption ccfe" separg="1"></option>            <!-- (no correspondence) Pass option X on to program ccfe -->
  <option name="Qoption cpp"  separg="1"></option>            <!-- (no correspondence) Pass option X on to program cpp -->
  <option name="qoption ccfe" separg="1"></option>            <!-- (no correspondence) Pass option X on to program ccfe -->
  <option name="qoption cpp"  separg="1"></option>            <!-- (no correspondence) Pass option X on to program cpp -->
  <option name="U"    immarg="1">-U%</option>                 <!-- Delete initial definition of preprocessor symbol X -->
  <option name="Xm"   noarg="1">--dollar</option>             <!-- Support dollar character in C++ identifiers  -->
  <option name="dryrun" noarg="1"></option>                   <!-- Show compiler commands built by driver, no compilation -->
  <option name="features" immarg="1"></option>                <!-- (no correspondence) Enables/disables various C++ language features -->
  <option name="pta"  noarg="1">--instantiate all</option>    <!-- Instantiate whole template class -->
  <option name="xwe"  noarg="1"></option>                     <!-- Convert all warnings to errors -->

  <option name="o" separg="1"/>                               <!-- output file -->
  <option name="Qdir" separg="1"/>
  <option name="Qpath" separg="1"/>
  <option name="Qoption c++filt" separg="1"/>                 <!-- Pass option X on to program c++filt -->
  <option name="Qoption cat" separg="1"/>                     <!-- Pass option X on to program cat -->
  <option name="Qoption cg" separg="1"/>                      <!-- Pass option X on to program cg -->
  <option name="Qoption fbe" separg="1"/>                     <!-- Pass option X on to program fbe -->
  <option name="Qoption iropt" separg="1"/>                   <!-- Pass option X on to program iropt -->
  <option name="Qoption ld" separg="1"/>                      <!-- Pass option X on to program ld -->
  <option name="Qoption prog" separg="1"/>                    <!-- Pass options list to compilation phase <prog> -->
  <option name="Qoption tdb_link" separg="1"/>                <!-- Pass option X on to program tdb_link -->
  <option name="qoption c++filt" separg="1"/>                 <!-- Pass option X on to program c++filt -->
  <option name="qoption cat" separg="1"/>                     <!-- Pass option X on to program cat -->
  <option name="qoption cg" separg="1"/>                      <!-- Pass option X on to program cg -->
  <option name="qoption fbe" separg="1"/>                     <!-- Pass option X on to program fbe -->
  <option name="qoption iropt" separg="1"/>                   <!-- Pass option X on to program iropt -->
  <option name="qoption ld" separg="1"/>                      <!-- Pass option X on to program ld -->
  <option name="qoption tdb_link" separg="1"/>                <!-- Pass option X on to program tdb_link -->
  <option name="Qproduce" separg="1"/>                        <!-- Produce file of given type -->
  <option name="qproduce" separg="1"/>                        <!-- Produce file of given type -->
  <option name="R" immarg="1" separg="1"/>                    <!-- Build runtime search path list into executable -->
  <option name="qpath" separg="1"/>                           <!-- Look for compiler passes in directory X first -->
  <option name="targ" separg="1"/>                            <!-- Set target architecture to arch-type -->
  <option name="xinline" immarg="1"/>                         <!-- Same as -inline, takes file names in brackets. -->

  <option intro="+" name="d" noarg="1"/>                      <!-- Do not expand inline functions -->
  <option intro="+" name="e0" noarg="1"/>                     <!-- virtual table external but only declared -->
  <option intro="+" name="e1" noarg="1"/>                     <!-- virtual table external and defined -->
  <option intro="+" name="p" noarg="1"/>                      <!-- Disallow anachronistic constructs -->
  <option intro="+" name="w2" noarg="1"/>                     <!-- Print warnings for all code potentially in error -->
  <option intro="+" name="w" noarg="1"/>                      <!-- Print extra warnings where necessary -->
</translate>
    -I%0%/include/CC
    -I%0%/include/CC/std
    -I%0%/include/CC/rw7
    -I%0%/include/cc
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/hpcc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<cmdline nameintro="-" unrecognized="no_message"><alternate nameintro="+"/>
<compilername>HP cc</compilername>
C -D__hp9000s800 -D__hppa -D__hpux -D__unix -D_PA_RISC2_0 -D__CLASSIC_C__ -I/usr/include --c --no_warnings -D_SIZE_T --diag_suppress 265 --microsoft --size_t_is_unsigned_long -Dhppa -Dhpux -Dunix -Dhp9000s800
  <translate>
    <option name="I" immarg="1" separg="1">-I%</option><!-- Add <dir> to preprocessor #include file search path -->
    <option name="D" immarg="1" separg="1">-D%</option><!-- Associate name with token as if by #define -->
    <option name="E" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to stdout -->
    <option intro="+" name="M" noarg="1">+M</option>            <!-- Print path names of included files -->
    <option name="P" noarg="1">-P</option>            <!-- Compile source through preprocessor only, output to .i  file -->
    <option name="U" immarg="1">-U%</option>          <!-- Delete initial definition of preprocessor symbol <name> -->
    <option intro="+" name="Z" noarg="1">+Z</option>            <!-- Causes the compiler to generate position-independent code (PIC),
                                                           necessary for building shared libraries.  -->
    <option intro="+" name="v" noarg="1">+w</option>            <!-- Do stricter semantic checking -->
    <option name="w" noarg="1">-w</option>            <!-- Suppress compiler warning messages -->
    <option name="YI" immarg="1">-I -I%</option>      <!-- Change default directory searched for include files -->

    <option name="o" separg="1"></option>             <!-- Set name of output file to <outputfile> -->
    <option name="b" noarg="1">-b</option>             <!-- Creates a shared library rather than an executable file -->
    <option name="c" noarg="1" />              <!-- Suppress linking -->
  </translate>
</cmdline>

=== kit-transue/software-emancipation-discover/parsercmd/data/mipscc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cmdline
  PUBLIC "-//THECOMPANY//DTD DISCOVER 7.3.x//EN"
  "cmdline.dtd">
<cmdline nameintro="-" unrecognized="no_message">
<compilername>MIPS C</compilername>
  <switch enable="ntt"/> <!-- default to n32 -->
  <translate>
    <option name="n32" noarg="1" enable="ntt"/>
    <option name="o32" noarg="1" enable="ott"/>
    <option name="64" noarg="1" enable="sf"/>
  </translate>
  <switch when="ott|sf" disable="ntt"/>
C
    -w
    --c
    --allow_error_directive
    -D__DISCOVER__
    -D_MIPS_SZINT=32
    -D_LONGLONG
    -D__EXTENSIONS__
    -Dsgi
    -D_SGI_SOURCE
    -D_LANGUAGE_C
    -D_MIPSEB
    -D__unix
  <switch when="ott"> <!-- o32 -->
    -D_MIPS_SIM=1
    -D_MIPS_FPSET=16
    -D_MIPS_SZLONG=32
    -D_MIPS_SZPTR=32
    -D_ABIO32=1
    -D_MIPS_ISA=2
  </switch>
  <switch when="ntt"> <!-- n32 -->
    -D_MIPS_SIM=2
    -D_MIPS_FPSET=32
    -D_MIPS_SZLONG=32
    -D_MIPS_SZPTR=32
    -D_ABIN32=2
    -D_MIPS_ISA=4
  </switch>
  <switch when="sf"> <!-- 64 -->
    -D_MIPS_SIM=3
    -D_MIPS_FPSET=32
    -D_MIPS_SZLONG=64
    -D_MIPS_SZPTR=64
    -D_ABI64=3
    -D_MIPS_ISA=4
  </switch>
  <translate>
    <option name="D" immarg="1">-D%</option>          <!-- Associate name with token as if by #define -->
    <option name="E" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to stdout -->
    <option name="I" immarg="1">-I%</option>          <!-- Add <dir> to preprocessor #include file search path -->
    <option name="P" noarg="1">-E</option>            <!-- Compile source through preprocessor only, output to .i  file -->
    <option name="U" immarg="1">-U%</option>          <!-- Delete initial definition of preprocessor symbol <name> -->
    <option name="v" noarg="1"></option>              <!-- Do stricter semantic checking -->
    <option name="w" noarg="1"></option>              <!-- Suppress compiler warning messages -->
    <option name="Xa" noarg="1">-xansi</option>       <!-- Compile assuming ANSI C conformance, allow K & R extensions (default mode) -->
    <option name="Xc" noarg="1">-ansi</option>        <!-- Compile assuming strict ANSI C conformance -->
    <option name="Xm" noarg="1">-dollar</option>      <!-- Support dollar character in C++ identifiers  -->
    <option name="Xs" noarg="1">-cckr</option>        <!-- Compile assuming (pre-ANSI) K & R C style code -->
    <option name="Xt" noarg="1">-xansi</option>       <!-- Compile assuming K & R conformance, allow ANSI C -->
    <option name="xCC" noarg="1">-Xcpluscomm</option> <!-- Accept C++ style comments -->
    <option name="xsfpconst" noarg="1">-float_const</option>      <!-- Represent unsuffixed floating point constants as single precision -->
    <option name="YI" immarg="1"></option>            <!-- Change default directory searched for include files -->

    <option name="o" separg="1"></option>             <!-- Set name of output file to <outputfile> -->
  </translate>
</cmdline>
